# 监测分支，2020年10月后github新建仓库默认分支改为main，记得更改
on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
      - name: 安装 Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/
      - name: 发布到npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: `+ '${{secrets.npm_token}}'